### ISSUE TITLE
What is ReportPortal?

### ISSUE THREAD

**Issue by Tset-Noitamotua** [reportportal/agent-Python-RobotFramework#1]
Could you please clarify what ReportPortal is?

Cheers
Tset

**Comment by tkachoff** [comment]
You can see all related info on http://reportportal.io/#documentation

**Comment by Tset-Noitamotua** [comment]
Wow  ... thats what I was looking for for so long!

I suggest to put link to reportportal.io into README.

Moreover some screenshots would be really great so that one would see what it is about at first glance.

**Comment by DzmitryHumianiuk** [comment]
@Tset-Noitamotua 
made some updates in root Readme.

And also you can use next links

## Community / Support

* [**Slack chat**](https://reportportal-slack-auto.herokuapp.com)
* [UserVoice forum](https://rpp.uservoice.com/forums/247117-report-portal) Please share and vote for ideas
* Report Portal Google Group (comming soon)
* [GitHub Issues](https://github.com/reportportal/reportportal/issues)
* [Stackoverflow Questions](http://stackoverflow.com/questions/tagged/reportportal)
* [Twitter](http://twitter.com/ReportPortal_io)
* [Facebook](https://www.facebook.com/ReportPortal.io)
* [VK](https://vk.com/reportportal_io)
* [YouTube Channel](https://www.youtube.com/channel/UCsZxrHqLHPJcrkcgIGRG-cQ)

**Comment by DzmitryHumianiuk** [comment]
@Tset-Noitamotua 
and review next presentations
https://www.youtube.com/watch?v=Wti0mZbnnoU
https://www.youtube.com/watch?v=jqzFfVV0OvM
https://www.youtube.com/watch?v=VVe30w_xM1Y

**Comment by Tset-Noitamotua** [comment]
Thank you! I'll have a look.

**Comment by Tset-Noitamotua** [comment]
In readme of this repo (not root) I would suggest to link root repo or may be better the homepage, too -  like that:

Listener for RobotFramework to report results to [ReportPortal](http://reportportal.io)

**Comment by Tset-Noitamotua** [comment]
@DzmitryHumianiuk 
I have taken a closer look at documentation and also watched your presantations on youtube. Quite on question remains: When I set it up - will it run fully (100%) on my system (my infrastructure) or will it send results to your servers for analysys?

**Comment by DzmitryHumianiuk** [comment]
@Tset-Noitamotua if you install your own - it will send results only to your instance

**Comment by Tset-Noitamotua** [comment]
@DzmitryHumianiuk  Are there other options than installing on my own?
