### ISSUE TITLE
Attach screenshot to reportportal

### ISSUE THREAD

**Issue by AbdulAmrinSubair** [reportportal/agent-Python-RobotFramework#100]
### Versions:-
> - robotframework-reportportal    5.1.0
> - reportportal-client     5.0.10
> - robotframework     4.0.2
> - requests        2.25.1

Below is the python class with add attachment logic

```
import subprocess
from robotframework_reportportal import logger
class Customlogger:
     
    def log_free_memory(self,name):
        with open(name, "rb") as fh:
         
            file_data = fh.read()
            logger.info("Collecting free memory statistics!")
            logger.info("Some Text Here",attachment={"name": "test_name_screenshot.png","data": file_data, "mime": "image/png"})
             
```
             
Below is the .robot file

```
*** Settings ***
Library           SeleniumLibrary   
Library           Collections
Library    Customlogger.py


*** Keywords ***
Capture image
   ${path}   Capture Page Screenshot
   Log Free Memory  ${path}


*** Test Cases ***
Sample Test
    Open Browser  https://www.google.com    chrome
    Capture image
            
```

Both the files are in the same folder structure.

Actual:-
Keywords and test are displayed in the reportportal except screenshots

Expected:-
Screenshot should be attached

**Comment by iivanou** [comment]
@AbdulAmrinSubair Change your .robot file the way below and let us know the results. Thanks.
```
*** Settings ***
Library           SeleniumLibrary   
Library           Collections
Library    Customlogger.py


*** Test Cases ***
Sample Test
    Open Browser  https://www.google.com    chrome
    ${path}   Capture Page Screenshot
    Log Free Memory  ${path}
```

**Comment by AbdulAmrinSubair** [comment]
![Screen Shot 2021-05-12 at 9 41 46 AM](https://user-images.githubusercontent.com/79517279/117937488-56a8a280-b306-11eb-98fe-53c086e0808d.png)


@iivanou no screenshot attached yet

**Comment by iivanou** [comment]
@AbdulAmrinSubair Can you apply changes from #101? They should fix the problem.

**Comment by AbdulAmrinSubair** [comment]
@iivanou i tried but nothing changed

**Comment by iivanou** [comment]
![image](https://user-images.githubusercontent.com/8349078/117959611-dc3b4b00-b324-11eb-84e9-2e1580191bd2.png)
![image](https://user-images.githubusercontent.com/8349078/117959831-0e4cad00-b325-11eb-8985-4f5b48ec11d7.png)

**Comment by AbdulAmrinSubair** [comment]
@iivanou  i confirm that screenshot works now!

**Comment by AbdulAmrinSubair** [comment]
@iivanou i think the issue is due to
https://github.com/reportportal/agent-Python-RobotFramework/issues/102

**Comment by AbdulAmrinSubair** [comment]
@iivanou 
#100 issue still exists
![Screen Shot 2021-05-14 at 1 43 26 PM](https://user-images.githubusercontent.com/79517279/118266128-77195e00-b4ba-11eb-93b8-1805b838d62f.png)

tried version robotframework-reportportal v5.1.1 but still screenshots aren't attached 
#102 is fixed

**Comment by iivanou** [comment]
Version 5.1.1 has not been released yet.
