### ISSUE TITLE
 keyword level implementation not visible in reportportal and this impacts debugging capability

### ISSUE THREAD

**Issue by AbdulAmrinSubair** [reportportal/agent-Python-RobotFramework#102]
As a user i would like to see the user defined keyword implementation of tests to debug test failure.
Currently user defined keyword with capture image  doesn't really display the image unless it's defined in test case level

Actual:-
Currently only keywords mentioned in test case level are displayed in reportportal

Expected:-
Keywords names and their internal implementation should also be shown in both test case and keyword level

**Comment by iivanou** [comment]
A fix for #100 will fix this one as well.
