### ISSUE TITLE
plugin logging too much data (as following from robot loglevel defined)

### ISSUE THREAD

**Issue by doguz2509** [reportportal/agent-Python-RobotFramework#106]
---
name: Too much data printed within robot log & report
about: Reduce log data
title: redirect plugin output in separate stream
labels: bug
assignees: ''

---

Too much data printed within robot log & report

When robot tests run with flag -L TRACE/DEBUG it following with too much report plugin info not related to test itself

**Expected behavior**
Report plugin can log into:
- file 
- console

**Actual behavior**
When DEBUG or TRACE level defined too much data in log & report making trouble to understand test output itself

**Package versions**
robotframework-reportportal

**Comment by iivanou** [comment]
@doguz2509 What exactly data is considered to be excessive from your point of view? I need more details. Currently, the description along with expected and actual behaviour looks superficial.

**Comment by doguz2509** [comment]
All DEBUG/TRACE info printed by reportportal plugin not relevant for the test context and make difficult test result analyze. 
I looking for option separate it from my test report

**Comment by doguz2509** [comment]
I used old report portal agent version (5.0.1)
After upgrade to newer one (5.1.1) it can be solved as described above
But I made it together with upgrade robot to 4.0.2 and got another error
Will be described in separate issue
