### ISSUE TITLE
Is RP_LAUNCH_UUID required for Pabot runs?

### ISSUE THREAD

**Issue by grahamhome** [reportportal/agent-Python-RobotFramework#113]
https://github.com/reportportal/agent-Python-RobotFramework/blob/575cb1718e0f109384643218a82b42c5a6ec5cea/robotframework_reportportal/listener.py#L127

It appears that this plugin cannot create new ReportPortal launches when run with Pabot. It must be given the UUID of an existing launch to send results to or the `Pabot library is used but RP_LAUNCH_UUID was not provided.` error will occur. Why is this so? Is there a workaround for now, and when can we expect a fix? Thanks in advance for your help.

**Comment by grahamhome** [comment]
@iivanou Ivan, do you have any knowledge about this limitation? Thanks in advance.

**Comment by iivanou** [comment]
@grahamhome It's not possible for us to create a launch with pabot before it starts running test suites. Pabot does not provide any instruments to do something before test suites are distributed across processes. So, in this case, we can report test suites into the separate launches only. And it does not seem to be correct.

**Comment by grahamhome** [comment]
@iivanou Thanks for the explanation.
