### ISSUE TITLE
RP_ATTACH_REPORT doesnt work

### ISSUE THREAD

**Issue by NikoHeikki** [reportportal/agent-Python-RobotFramework#114]
**Describe the bug**
Robot report is not uploaded into report portal even if RP_ATTACH_REPORT is set to true, report cant be found in portal

**Steps to Reproduce**
1. Run robot test and include --variable RP_ATTACH_REPORT:"true" into run command
2. Test passes
3. You can see new Launch
4. There are no attachments, didnt upload robot report

**Expected behavior**
Robot report is visible in Launch Attachments tab

**Actual behavior**
Robot report is not visible in anywhere in report portal

**Package versions**
Include version info of the following packages: reportportal-client, robotframework-reportportal-5.1.2

**Additional context**

**Comment by iivanou** [comment]
@NikoHeikki What version of reportportal-client are you using? You have to update reportportal-client to version 5.0.11.

**Comment by NikoHeikki** [comment]
@iivanou Im using robotframework-reportportal==5.1.2 and reportportal-client==5.0.11

**Comment by iivanou** [comment]
Can you share a screenshot of where you are looking for the attachment? Everything works on my side...

**Comment by NikoHeikki** [comment]
<img width="1656" alt="Screenshot 2021-05-27 at 16 03 21" src="https://user-images.githubusercontent.com/29404248/119830593-1a2f9600-bf05-11eb-9e87-63cf9d634681.png">

**Comment by NikoHeikki** [comment]
it should be there ?@iivanou

**Comment by iivanou** [comment]
No, it should be here:

![image](https://user-images.githubusercontent.com/8349078/119833129-84493a80-bf07-11eb-964d-a9c77d75e829.png)

**Comment by NikoHeikki** [comment]
aaahhh, my bad, it is there and it works. That seems little unclear place for it, in my opinion. I could'nt find it, I looked for hours :D

**Comment by iivanou** [comment]
Yeah, it's not the best placement:)
