### ISSUE TITLE
Readme Needs Update

### ISSUE THREAD

**Issue by grahamhome** [reportportal/agent-Python-RobotFramework#115]
[Line 57 of the readme](https://github.com/reportportal/agent-Python-RobotFramework/blame/master/README.md#L57) indicates that the `RP_LAUNCH_UUID` parameter is optional. However, this parameter is required for the plugin to work - [see this comment for an explanation of why that is so](https://github.com/reportportal/agent-Python-RobotFramework/issues/113#issuecomment-849326875).

Please update the documentation to indicate that this parameter is required, not optional, and please provide instructions on how to obtain it - is there a utility method within this plugin which can be called to create a new launch and retrieve the launch UUID?

**Comment by grahamhome** [comment]
@iivanou I have opened this issue based on the discussion we had about [Issue 113](https://github.com/reportportal/agent-Python-RobotFramework/issues/113).

**Comment by iivanou** [comment]
This parameter is required when you use pabot only. For executions with Robot Framework, it is optional. Requested utilities and methods are not included in this library. The agent is considered to be used by Robot Framework itself. 

@HardNorth , do we have an example of an API request that creates a new launch documented somewhere? Maybe it makes sense to add this information into the README.

**Comment by grahamhome** [comment]
I was able to resolve this issue independently using the reportportal/client-Python library.

**Comment by HardNorth** [comment]
@iivanou Something like that:
```shell
curl --location --request POST 'http://localhost:8080/api/v1/default_personal/launch' \
--header 'Authorization: Bearer your_api_token_here' \
--header 'Content-Type: application/json' \
--data-raw '{
  "attributes": [
    {
      "key": "key",
      "value": "value"
    }
  ],
  "description": "Launch description",
  "mode": "DEFAULT",
  "name": "Launch name",
  "startTime": "2021-05-28T08:03:05.063Z"
}'
```

Response:
```json
{
    "id": "770d2822-877a-45aa-904f-5e11921079d0",
    "number": 1
}
```
