### ISSUE TITLE
robotframework_reportportal.logger not working with Pabot

### ISSUE THREAD

**Issue by grahamhome** [reportportal/agent-Python-RobotFramework#116]
Is the `robotframework_reportportal.logger` class documented in the Readme able to be used with Pabot? We are not seeing any log messages appear when calling `logger` methods with or without attachments.

@iivanou Do you know if this should be possible? Thanks in advance for your help.

**Comment by iivanou** [comment]
@grahamhome It is able to send logs with Pabot. Can you share how you use it? Thanks.
