### ISSUE TITLE
In a test execution with an IF-ELSE IF condition sometimes the ELSE IF block is being marked as Failed even when the IF condition succeeds when logging to reportportal

### ISSUE THREAD

**Issue by prajeeth07** [reportportal/agent-Python-RobotFramework#129]
---
name: Bug report
title: 'Issue observed when logging the results from robotframework back to reportportal'
labels: bug
assignees: ''

---

**Describe the bug**
When tests are executed on Docker, sometimes for tests having an IF-ELSE IF logic, the ELSE IF block is marked as Failed (however, the steps inside the ELSE block are shown as Skipped.) on reportportal. 
The HTML report generated by Robotframework shows the test as passed.
A similar issue is observed sometimes on the high-level keyword which is marked as Failed when none of the lower level keywords has failed - only on reportportal results.

**Steps to Reproduce**
- Execute the robotframework tests on docker
- set the RP_ATTACH_REPORT:"True" in the run command to access the robotframework generated HTML report

**Expected behavior**
The step should be marked as Skipped similar to robotframework reportportal results

**Actual behavior**
Sometimes the ELSE IF or ELSE block is marked as failed even when the IF block is successful and marked as Passed

Screenshot: 
ReportPortal screenshot for the test executed on docker:
![image](https://user-images.githubusercontent.com/41963549/124786521-adfe7400-df3f-11eb-8e14-f895f7eb7dfb.png)

Robotframework HTML report attached along with the above execution. Only report.html is attached:
![image](https://user-images.githubusercontent.com/41963549/124788279-1e59c500-df41-11eb-9591-e15e9f839382.png)

Robotframework HTML report when executed locally with detailed steps:
![image](https://user-images.githubusercontent.com/41963549/124785960-392b3a00-df3f-11eb-92ad-fe90f82d01d9.png)

**Package versions**
-Lib Versions used - robotframework - 4.0.3
                                 robotframework-reportportal - 5.2.0

Note: The issue is observed intermittently on random tests. The test in the above-attached screenshots does not fail every time.

**Comment by HardNorth** [comment]
@prajeeth07 It looks like a very complex case. Could you please provide a project to reproduce the issue?

**Comment by prajeeth07** [comment]
@HardNorth I did try to increase the log level to TRACE and debug this but there is no information logged on why it happens.
Seems like an issue with the listener when logging back to reportportal - not entirely sure though.
So when a keyword has IF / ELSE it fails (rather than marking it as Skip) as I mentioned above OR at times just marks the high-level keyword which has an IF/ELSE block as Failed even though none of the steps inside the keyword fails

Also, as I mentioned above this happens intermittently, so not sure how to share an example for reproducibility.
I will try to get back to you with a sample test using a public website if possible.

**Comment by iivanou** [comment]
The listener sends out to RP exactly what it receives from the Robot Framework. There is not additional logic hidden in the agent that may impact keyword/test/suite status.

**Comment by HardNorth** [comment]
@prajeeth07 We won't able to debug without an example project :-/

**Comment by HardNorth** [comment]
Abandoned
