### ISSUE TITLE
Test steps under Before/After Suites are not displayed in List view of reportportal UI.

### ISSUE THREAD

**Issue by arvip** [reportportal/agent-Python-RobotFramework#139]
**Describe the bug**
Suite Setup and Suite Teardown of RobotFramework are shown as 'Before Suite and After Suite' in Reportportal UI. However, the test-steps under these suites show only in Log view and not in List view of Reportportal. See attached pictures for more clarification.

**Steps to Reproduce**
1. Create a file called before_after_hooks.robot with Suite Setup and Suite Teardown methods and a few testcases.
2. Run the above robot file through the reportportal_listener. 
3. In ReportPortal UI, open the above testcase. It displays the Before Suite, Testcases, After Suite in List view.
4. While in List view, select either the Before/After Suite -> An empty page is diplayed.
5. Repeat steps 3-4 while in Log View which displays the test-steps of Before/After Suite correctly.

**Expected behavior**
At step 4, the test steps of Before/After Suite should also be shown in List View. Not an empty page.

**Actual behavior**
An empty page is displayed while viewing test steps in Before/After Suite using List view. 

**Package versions**
reportportal-client - 5.1.0
robotframework-reportportal - 5.2.1

**Additional context**
See attachment for more detailed views.
![listview_1](https://user-images.githubusercontent.com/16577883/152794466-c1cc0226-4fd2-4e10-b20d-8d529c6fce9c.PNG)
![listview_2](https://user-images.githubusercontent.com/16577883/152794471-8e86ee2d-7821-47c4-9fdb-1b150598e78a.PNG)
![logview](https://user-images.githubusercontent.com/16577883/152794473-a686b7b6-1580-46aa-be46-215847282c2f.PNG)

**Comment by patelilesh32** [comment]
Is there any work around for this issue. I am also facing similar issue
