### ISSUE TITLE
RP Logging - Robot Automation Framework

### ISSUE THREAD

**Issue by anupkkumarfb** [reportportal/agent-Python-RobotFramework#142]
---
name: Bug report
about: Create a report to help us improve
title: ''
labels: bug
assignees: ''

---

**Describe the bug**
After adding listeners to my robot test trigger command, I dont see my framework's native log message on the console.  

**Steps to Reproduce**
Run the below command:

robot -V config/credential.yaml --variable EXECUTION_MODE:LOCAL --listener robotframework_reportportal.listener --variable RP_ATTACH_LOG:"True" --variable RP_UUID:abc-def-geh --variable RP_ENDPOINT:http://reportportal:8080/ --variable RP_LAUNCH:anup_sample_925pm --variable RP_PROJECT:superadmin_personal -i Sanity testsuites/abc.robot

**Comment by HardNorth** [comment]
@anupkkumarfb I've tried our examples, both with and without our listener, and their outputs are identical, they both contains logs I logged with 'Log' keyword.  Could you please provide examples of how you log your messages and how the output looks like?

**Comment by HardNorth** [comment]
Abandoned
