### ISSUE TITLE
[V5] RP Launches created by robotframework - take a lot of time to get uploaded to Report Portal

### ISSUE THREAD

**Issue by smartykhare** [reportportal/agent-Python-RobotFramework#143]
**Describe the bug**
Report Portal Launches take a lot of time to get uploaded to Report Portal

**Steps to Reproduce**
1. Write a sample testcase to log a message: 
TestCase1
    Log    Hello World    
2. Run the testcase with robot command - robot C:\UTF_Setup\UTF\UnifiedTestFramework\UAT_Tests\SampleTests\SamplePrint\HelloWorld.robot
Result - Testcase takes 0.038 sec to execute
![image](https://user-images.githubusercontent.com/96837986/161605244-269998b2-fcba-4148-a048-1e800bb67540.png)

Now run the same testcase with Report Portal listener:
robot --listener robotframework_reportportal.listener --variable RP_UUID:abc-def-ghi --variable RP_ENDPOINT:https://reportportal.perf.fusionfabric.io --variable RP_LAUNCH:sample_test --variable RP_PROJECT:deepalee_khare_personal C:\UTF_Setup\UTF\UnifiedTestFramework\UAT_Tests\SampleTests\SamplePrint\HelloWorld.robot
Result - Testcase takes 8 sec to execute
![image](https://user-images.githubusercontent.com/96837986/161605677-d19e5816-6cd7-4171-8efa-044f1aac89b9.png)

**Expected behavior**
Both the scenarios should take the same time to execute

**Actual behavior**
This bug is creating a huge difference in a larger number of testcases - for example - if I have 150 testcases (API & UI) - it takes 3 mins to execute. But along with the ReportPortal Listener - it takes 30 mins to execute. :O (Unexpected!).
Also, the report portal takes a lot of time to update the launches - for example, if 50/150 testcases are completed, the report portal will show only around 16 testcases completed. But when given time - it will slowly update all the launches - and the time taken matches with the output.xml file

**Package versions**
ReportPortal - deployed using Kubernetes = 5.6.3
reportportal-client = 5.1.0 
robotframework-reportportal = 5.2.1
RobotFramework = 3.2.2.1

**Additional context**
Earlier I was using robotframework-reportportal_ng with the 4.2 version of the report portal - And it was working as expected - that is - test cases were running on time.

**Comment by smartykhare** [comment]
@HardNorth, @iivanou Could you please help me?

**Comment by HardNorth** [comment]
I'm afraid this is not possible in the nearest future.
