### ISSUE TITLE
Robot Framework attachments are not present in ReportPortal

### ISSUE THREAD

**Issue by lmazureNX** [reportportal/agent-Python-RobotFramework#148]
**Describe the bug**
My configuration:
- ReportPortal 5.7.2 in Docker in WSL2 on my laptop
- I am running some simple tests Robot Framework tests (https://gitlab.com/m4711/robotframework-samples)
- I try to push their results in ReportPortal (using gitbash in Windows on my laptop)

**Steps to Reproduce**
1. I run the test with the command line
```bash
robot --outputdir reports --listener robotframework_reportportal.listener --variable RP_UUID:"b58f8cf0-56a1-44eb-a1ca-45453d5302bc" --variable RP_ENDPOINT:"http://127.0.0.1:8080" --variable RP_LAUNCH:"my ROBOTFRAMEWORKSAMPLES launch" --variable RP_PROJECT:"ROBOTFRAMEWORKSAMPLES" --xunit junit_report.xml --variable RP_ATTACH_XUNIT:"True" --variable RP_ATTACH_REPORT:"True" --variable RP_ATTACH_LOG:"True" mazure.robot
```
2. In ReportPortal, I can see the test results :
![image](https://user-images.githubusercontent.com/86486919/188164960-fc3dfacb-3c86-4023-8790-6f024854dae1.png)
the "stack trace"
![image](https://user-images.githubusercontent.com/86486919/188165065-1d533e78-1fe8-428a-944c-f780dcd7d86a.png)
but no attachment
![image](https://user-images.githubusercontent.com/86486919/188165190-96848c1d-9703-4024-b1c4-b8489a693508.png)

**Expected behavior**
Given the command line I used (`--variable RP_ATTACH_XUNIT:"True" --variable RP_ATTACH_REPORT:"True" --variable RP_ATTACH_LOG:"True"`), I was expecting to see
- report.html
- log.html
- junit_report.xml

**Actual behavior**
No attachement is present.

**Package versions**
The Python modules are
```bash
$ pip list | grep report
reportportal-client             5.2.3
robotframework-reportportal     5.3.0
```

**Additional context**

**Comment by HardNorth** [comment]
@lmazureNX Please look for reports in the root of `my ROBOTFRAMEWORKSAMPLES launch` (you need to click on `my ROBOTFRAMEWORKSAMPLES launch #22` breadcrumb and open `LOG VIEW` tab).

**Comment by lmazureNX** [comment]
@HardNorth Sorry... PEBCAK Thanks for you help!
