### ISSUE TITLE
Teststatus is marked incorrectly, appears as overwritten.

### ISSUE THREAD

**Issue by FloSch-Nokia** [reportportal/agent-Python-RobotFramework#151]
Since a few days, some of our results are marked with a wrong status (Failed instead of Passed). For the tests that are marked incorrectly, I can see a action in the History of Actions ( see screenshot )

<img width="696" alt="image" src="https://user-images.githubusercontent.com/24247464/186141579-8b00f887-ca71-4080-917e-99a0ec2628a4.png">

But this action was definitely not triggered by a user. The Robot Framework results are uploaded via post_report.
I also post_reported it against a different project, but still experience the same behavior. 

**Versions:**
 - Version of RP is 5.7.1

**Comment by HardNorth** [comment]
@FloSch-Nokia What is your version of Robot Framework?

**Comment by FloSch-Nokia** [comment]
Rf is 5.0.1

**Comment by HardNorth** [comment]
Looks like it's fixed in `5.4.0`.
