### ISSUE TITLE
robotframework_reportportal.listener failed: TypeError: Object of type _PresenceSentinel is not JSON serializable.

### ISSUE THREAD

**Issue by wshdota2** [reportportal/agent-Python-RobotFramework#154]
There are lot of methods in robotframework_reportportal.listener failed: TypeError: Object of type _PresenceSentinel is not JSON serializable.
```
robotframework :    Window 10
reportprotal :       Centos 8
reportportal-client         5.2.5
robotframework              3.2.1
robotframework-reportportal 5.3.0
```

![1666233331(1)](https://user-images.githubusercontent.com/51727190/196842850-c76aa95e-3413-46ff-91bd-58ce12830b77.png)

**Comment by HardNorth** [comment]
@wshdota2 Please take a look on the first error, it tells you clearly what's wrong.
Also please examine our property documentation: https://github.com/reportportal/agent-Python-RobotFramework#properties
