### ISSUE TITLE
[ ERROR ] Calling method '_start_suite' of listener 'DataDriver' failed: ImportError: Pandas requires version '3.0.7' or newer of 'openpyxl' (version '3.0.5' currently installed).

### ISSUE THREAD

**Issue by ajaykumarab** [reportportal/agent-Python-RobotFramework#155]
[ ERROR ] Calling method '_start_suite' of listener 'DataDriver' failed: ImportError: Pandas requires version '3.0.7' or newer of 'openpyxl' (version '3.0.5' currently installed).

**Comment by HardNorth** [comment]
The error states it's clear, please update `pandas` library. Apart from that your issue doesn't follow our template.
