### ISSUE TITLE
[ ERROR ] Parsing 'Robot_Keywords.robot' failed: File or directory to execute does not exist.  Try --help for usage information.

### ISSUE THREAD

**Issue by ajaykumarab** [reportportal/agent-Python-RobotFramework#157]
**Describe the bug**
Path is missing

**Steps to Reproduce**
1. How to solve this error

**Expected behavior**

**Actual behavior**
What actually happened.

**Package versions**
Include version info of the following packages: reportportal-client, robotframework-reportportal

**Additional context**

**Comment by ajaykumarab** [comment]
Solve this issue

**Comment by HardNorth** [comment]
Duplicates #156
