### ISSUE TITLE
[ ERROR ] Parsing 'DDT2.robot' failed: File or directory to execute does not exist.  Try --help for usage information.

### ISSUE THREAD

**Issue by ajaykumarab** [reportportal/agent-Python-RobotFramework#158]
**Describe the bug**

**Steps to Reproduce**
1. 
![image](https://user-images.githubusercontent.com/103194097/198216680-9dbf9b8d-3aa4-4175-87d9-b2bb5edfc33d.png)

**Expected behavior**

**Actual behavior**
What actually happened.

**Package versions**
Include version info of the following packages: reportportal-client, robotframework-reportportal

**Additional context**

**Comment by ajaykumarab** [comment]
I have facing this issues ,solve this

**Comment by HardNorth** [comment]
Duplicates #156
