### ISSUE TITLE
problem about listener

### ISSUE THREAD

**Issue by theeraweej** [reportportal/agent-Python-RobotFramework#159]
hi

i am trying to run an simple example and found following errors

```
[ ERROR ] Calling method 'start_suite' of listener 'robotframework_reportportal.listener' failed: TypeError: Object of type _PresenceSentinel is not JSON serializable
[ ERROR ] Calling method 'start_test' of listener 'robotframework_reportportal.listener' failed: TypeError: Object of type _PresenceSentinel is not JSON serializable
[ ERROR ] Calling method 'start_keyword' of listener 'robotframework_reportportal.listener' failed: AttributeError: 'NoneType' object has no attribute 'type'
[ ERROR ] Calling method 'log_message' of listener 'robotframework_reportportal.listener' failed: TypeError: Object of type _PresenceSentinel is not JSON serializable
[ ERROR ] Calling method 'end_keyword' of listener 'robotframework_reportportal.listener' failed: IndexError: pop from empty list
[ ERROR ] Calling method 'end_test' of listener 'robotframework_reportportal.listener' failed: AttributeError: 'NoneType' object has no attribute 'update'
Simple test                                                           | PASS |
------------------------------------------------------------------------------
[ ERROR ] Calling method 'end_suite' of listener 'robotframework_reportportal.listener' failed: IndexError: pop from empty list
Simple                                                                | PASS |
1 test, 1 passed, 0 failed
```

here is my command.

`robot --listener robotframework_reportportal.listener -v RP_UUID:<uuid> -v RP_ENDPOINT:"http://localhost:8080" -v RP_LAUNCH:"launch_name_1" -v RP_PROJECT:"Test1" simple.robot`

i have no idea how to fix it. please help on this.
Thanks

**Comment by theeraweej** [comment]
do i need to do anything on start_suite, start_test, start_keyword, log_message, end_keyword, end_test?

**Comment by restagner** [comment]
@theeraweej ,

I am seeing the exact same issue.  I'm new to python's version of report portal and just started to try to use if on Friday.  Have you been able to figure out a solution for your issue?

**Comment by iivanou** [comment]
@restagner I'd request a list of installed python packages as the first step. Most likely you have multiple packages with listeners in your environment  and Robot picks up the broken one. This is of the top of my head.

**Comment by iivanou** [comment]
Also, it would be nice if you Guys can follow the Bug report template creating a new issue. This particular issue is missing a lot of details required to be shared to reproduce the problem or even to make a guess about the root cause.

**Comment by restagner** [comment]
@iivanou ,

Thanks for your timely responses.  This is no longer an issue for me.  We received the incorrect RP_PROJECT value and were attempting to use this value to connect to Report Portal.  Once we had the correct value, everything worked as expected

**Comment by HardNorth** [comment]
@theeraweej I believe you need to check properties you bypass to the agent as Robert. You can enable request/response logging setting `HTTPConnection.debuglevel` to `1` somewhere in your code as here: https://github.com/reportportal/examples-python/blob/master/pytest/tests/conftest.py#L24
It should give you insights which exact property is incorrect.
