### ISSUE TITLE
HELP NEEDED: Not able to run robot file integration with report-portal

### ISSUE THREAD

**Issue by subha0990** [reportportal/agent-Python-RobotFramework#171]
I am trying to integrate Report portal  with Robot FW.
robotframework                 4.1.3
robotframework-reportportal    3.1.1

With reportportal-client            5.4.0

[ ERROR ] Taking listener 'robotframework_reportportal.listener' into use failed: Importing listener 'robotframework_reportportal.listener' failed: ImportError: cannot import name 'ReportPortalServiceAsync' from 'reportportal_client' (C:\Python3.9\Lib\site-packages\reportportal_client\__init__.py)

 

2. With reportportal-client            3.2.3

 

[ ERROR ] Calling method 'start_suite' of listener 'robotframework_reportportal.listener' failed: RobotServiceException: Missing parameter RP_UUID for robot run

Parameters passed like below
--listener
robotframework_reportportal.listener
--variable
RP_API_KEY:"hmv3uNZlnhmxvZjJSgiN3ki439g"
--variable
RP_ENDPOINT:"http://localhost:8080/ui/#login"
--variable
RP_LAUNCH:"Subha_RobotFW_ReportPortal"
--variable
RP_PROJECT:"superadmin_personal"
C:\Subha-RFW\subha1.robot

**Comment by HardNorth** [comment]
@subha0990 Please use newer version of `robotframework-reportportal` agent, `3.1.1` is not suitable to work with the latest versions of `reportportal-client` and Report Portal itself.

**Comment by subha0990** [comment]
Kindly mention which versions to be used for below for not getting any compatible issue ?
robotframework-reportportal 
reportportal-client 
six 
python-dateutil

**Comment by HardNorth** [comment]
@subha0990 Latest one.

**Comment by subha0990** [comment]
hi
Kindly help

I deploy report portal by docker.
I am able to login as default user access.
I want to login as superadmin (Admin access)

superadmin /erebus

URL:- http://localhost:8080/ui/#login

Kindly help ASAP
[image: image]
<https://user-images.githubusercontent.com/140379815/256435925-ac959d0b-8243-4c06-8065-6d823b642adf.png>
=============Request URL:=======================
http://localhost:8080/uat/sso/oauth/token
Request Method:
POST
Status Code:
400 Bad Request
Remote Address:
[::1]:8080
Referrer Policy:
strict-origin-when-cross-origin
======payload===========
grant_type=password&username=superadmin&password=erebus
============response=============
{
"errorCode": 4003,
"message": "You do not have enough permissions. Bad credentials"


Thanks

Subhakanta
