### ISSUE TITLE
Add 'metadata' parameters processing for Launch and Suite level

### ISSUE THREAD

**Issue by petr-kus** [reportportal/agent-Python-RobotFramework#178]
**Is your feature request related to a problem? Please describe.**
We now have many test suites in one launch. But we can't input the suite attribute. It is difficult to filter them and sort them.

**Describe the solution you'd like**
I would like to have available suite attribute settings the same way as launch attributes or tets attributes in parameters. At least. 

**Describe alternatives you've considered**
I considered my client which would access the API of the report portal and set it. But it is an unsystematic approach and I think more people appreciate this feature.

I considered transferring these suite attributes to launch attributes.
But, attributes for launch are limited in length so can't be all attributes from the suite transferred to launch. 
When there is too long an attribute you can't set it for launch (you give an error on API, level).

**Comment by HardNorth** [comment]
@petr-kus Please address this to [Robot Framework](https://github.com/robotframework/robotframework)
I don't feel like it's good idea to add something which is not supported by base Framework.

**Comment by petr-kus** [comment]
? What are you talking about, they already have metadata and many things for the suite context. 
I think we don't understand each other.

We of course just use their feature for suite Meta Data. (btw. it is almoste bug on your side becouse you take the suite atribute and move them to test atribute...)

I don't see what can I request from Robot Framework site top of it. Maybe just make a system for test result storage as report portal or test archiver (btw. in test archiver it is possible to handle). 

Your system just can't sort all results of tests accordingly (becouse I can't tell that a group of tests have the same metadata and your system don't do it yourself).

Roboto Framework don't support it at all, becouse they simply are not system for holding the resutls of tests. They are not interested in groups of tests. Just one suite.

But your system is, it is one form primarly goals of your system.

**Comment by HardNorth** [comment]
@petr-kus OK, looks like we missed Metadata attributes processing in our Agents. Then the issue should sound like "Add 'metadata' parameters processing for Launch and Suite level", rather than asking for adding additional parameters, which are completely not suitable in this case.

OK, I'll add missed functionality in the next release.

**Comment by HardNorth** [comment]
Implemented in: https://github.com/reportportal/agent-Python-RobotFramework/releases/tag/5.5.3
