### ISSUE TITLE
Calling method 'log_message' of listener 'robotframework_reportportal.listener' failed

### ISSUE THREAD

**Issue by bzukendap** [reportportal/agent-Python-RobotFramework#180]
**Describe the bug**
I'm trying to connect ReportPortal application to automatic tests in Robot Framework. 
I installed "robotframework-reportportal".
After running the test from CMD an error is logged, see below.
Environment: PC: Windows 11 -> Reportportal: Kubernetes cluster

**Steps to Reproduce**
1. I'm trying to set up tests with the following command: robot --listener robotframework_reportal.listener --variablefile configuration\reportal.resource tests\folder\test.robot

**Expected behavior**
The tests are run and the results are sent to ReportPortal.

**Actual behavior**
The following errors are logged:

TypeError: Object of type _PresenceSentinel is not JSON serializable
[ WARN ] Attempt to finish non-existent item
[ WARN ] Attempt to finish non-existent item
[ WARN ] ReportPortal None request failed
Traceback (most recent call last):
  File "C:\Program Files\Python310\Lib\site-packages\reportportal_client\core\rp_requests.py", line 128, in make
    return RPResponse(self.session_method(self.url, data=self.data, json=self.json, files=self.files,
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python310\Lib\site-packages\requests\sessions.py", line 637, in post
    return self.request("POST", url, data=data, json=json, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python310\Lib\site-packages\requests\sessions.py", line 575, in request
    prep = self.prepare_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python310\Lib\site-packages\requests\sessions.py", line 486, in prepare_request
    p.prepare(
  File "C:\Program Files\Python310\Lib\site-packages\requests\models.py", line 371, in prepare
    self.prepare_body(data, files, json)
  File "C:\Program Files\Python310\Lib\site-packages\requests\models.py", line 511, in prepare_body
    body = complexjson.dumps(json, allow_nan=False)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python310\Lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
          ^^^^^^^^^^^
  File "C:\Program Files\Python310\Lib\json\encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python310\Lib\json\encoder.py", line 258, in iterencode
    return _iterencode(o, 0)
           ^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python310\Lib\json\encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type _PresenceSentinel is not JSON serializable
[ ERROR ] Calling method 'log_message' of listener 'robotframework_reportportal.listener' failed: TypeError: Object of type _PresenceSentinel is not JSON serializable
[ WARN ] Attempt to finish non-existent item
[ WARN ] Attempt to finish non-existent item
[ WARN ] Attempt to finish non-existent item
[ WARN ] Attempt to finish non-existent launch

**Package versions**
reportportal-client                5.5.3
robotframework-reportportal        5.5.0

**Additional context**
Please help me.

**Comment by HardNorth** [comment]
@bzukendap Usually this error means there is something wrong with your configuration or server. `Attempt to finish non-existent item` means the item didn't start by some reason.
Please ensure you use correct endpoint URL and Credentials. Also you might need to enable HTTP debug to find out what server tells you, see:
https://stackoverflow.com/questions/10588644/how-can-i-see-the-entire-http-request-thats-being-sent-by-my-python-application

Or just here, if console logging is enough for you:
https://github.com/reportportal/examples-python/blob/24cee004b7888ce28a20fa04ebe023055e90d186/pytest/tests/conftest.py#L24

**Comment by bzukendap** [comment]
Thank you, the error was in the URL, it's coming through now.

But I have another question: why when a test contains a skipped step the whole test is marked as "Failed"? Is there any way to turn it off?

**Comment by HardNorth** [comment]
@bzukendap Which keyword are you using for step skip?

**Comment by bzukendap** [comment]
**I will give two examples:**

The test is marked as Passed in the final report from Robot Framework, according to my check it is really passed.
In ReportPortal the test is marked as Passed but inside the test some steps are marked as Failed which is confusing for me. These are the steps containing If conditions and the code line where the condition does not pass is marked as Failed. Logically this is wrong, just because a value does not satisfy a condition does not mean it is wrong.

![image](https://github.com/reportportal/agent-Python-RobotFramework/assets/29704199/91ae1cfe-1ffb-4793-a590-ed31bf828ef1)
![image](https://github.com/reportportal/agent-Python-RobotFramework/assets/29704199/0bc7ea93-171b-4b37-82b3-7a2f733b6cf6)
![image](https://github.com/reportportal/agent-Python-RobotFramework/assets/29704199/d2e7fb1c-ff57-493f-a15c-0db6aca2be25)

In the second example, the test in RobotFramework is again passed in my opinion.
But in ReportPortal the test is marked as Failed.
Inside the test, the steps containing IF conditions where some condition was not met are again marked as Failed. Yet this is exactly the same code as the example above with similar data. But the result is slightly different. But the step is still marked as Failed.
![image](https://github.com/reportportal/agent-Python-RobotFramework/assets/29704199/108e958c-c94b-47de-9d96-9e6a81cf5a35)
![image](https://github.com/reportportal/agent-Python-RobotFramework/assets/29704199/9227b8e3-41b0-43bc-b494-6fe1ffc55724)
![image](https://github.com/reportportal/agent-Python-RobotFramework/assets/29704199/f65156f6-f5ce-416e-8708-f4aa98797e03)
There is an inconsistency in evaluating the same situation.
Moreover, if I have a condition where only one of the paths is satisfied, which is normal for IF, there is no reason to mark that step as Failed.

**Comment by HardNorth** [comment]
@bzukendap I tried to reproduce your case, but my example passes fine:
https://github.com/reportportal/examples-python/blob/master/robotframework/robot/if_skip.robot

Could you please try to implement an example which reproduces the case?

BTW I see missed keyword names in steps, that's shouldn't happen. But this is a separate case, probably related to newer versions of Robot Framework.

**Comment by HardNorth** [comment]
Abandoned
