### ISSUE TITLE
[ ERROR ] Calling method 'start_test' of listener 'robotframework_reportportal.listener' failed: FileNotFoundError: [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by golfzaptw** [reportportal/agent-Python-RobotFramework#183]
**Describe the bug**
After PASSED the first test case and continue the next test case, it show error `[ ERROR ] Calling method 'start_test' of listener 'robotframework_reportportal.listener' failed: FileNotFoundError: [Errno 2] No such file or directory`

**Steps to Reproduce**
1. Run command

robot -d log -o output.xml -l log.html -r report.html -x xunit.xml -b debug.txt -L DEBUG --listener robotframework_reportportal.listener -V report_portal.yaml -v 'RP_LAUNCH:Jenkins Sequential Launch' -v 'RP_LAUNCH_DOC:Robot framework launch sequential on Jenkins' -v 'RP_LAUNCH_ATTRIBUTES:tag APP_VERSION:842 JENKINS_BUILD_NUMBER:142' -v TEST_PLATFORM:android -v ENV:uat -v LANG:en -v APP:/Users/jenkins/842.apk -v FULLRESET_FLAG:true -v IS_LOCAL:false  -i logout_feature ./testcases/mobile

2. report_portal.yaml
```
RP_ENDPOINT: "<URL>"
RP_API_KEY: "<KEY>"
RP_PROJECT: "superadmin_personal"
RP_ATTACH_REPORT: "True"
RP_ATTACH_LOG: "True"
```

**Expected behavior**
Test result push to Report portal correctly

**Actual behavior**
![image](https://github.com/reportportal/agent-Python-RobotFramework/assets/21608972/626db804-e36a-4ba1-a6c3-9f97920c17df)
![image](https://github.com/reportportal/agent-Python-RobotFramework/assets/21608972/a3ed2549-d607-4f10-9ba8-cff18f6c6ac6)

**Package versions**
robotframework-reportportal==5.5.1
reportportal-client==5.5.4
robotframework==5.0

**Additional context**

**Comment by HardNorth** [comment]
@golfzaptw Please provide Traceback from Robot's debug logs (`robot -L trace -b debug.log`), because we actually do not read any files on `start_test` method call.

**Comment by HardNorth** [comment]
No response
