### ISSUE TITLE
to_timestamp() is not Timezone aware and leads to wrong times in ReportPortal

### ISSUE THREAD

**Issue by d0b3rm4n** [reportportal/agent-Python-RobotFramework#188]
See:
https://github.com/reportportal/agent-Python-RobotFramework/blob/bbceeb50b54ae085e74fa9fde13101c331301a77/robotframework_reportportal/result_visitor.py#L33

I had always wrong times in Report Portal. I fixed it with:

```python
from datetime import datetime, timedelta, timezone

def to_timestamp(time_str):
    if time_str:
        time = datetime.strptime(
            time_str, '%Y%m%d %H:%M:%S.%f').replace(tzinfo=timezone.utc)
        return str(int(time.timestamp() * 1000))
    return None
```

**Comment by HardNorth** [comment]
@d0b3rm4n These timestamps are being written in the local timezone, thus were you need UTC, one might need EST, or any other timezone. The only things I can do here is to add timezone configuration variable.

**Comment by HardNorth** [comment]
@d0b3rm4n Please use this version: https://github.com/reportportal/agent-Python-RobotFramework/releases/tag/5.5.6
