### ISSUE TITLE
how to add new test case execution to existing Launch?

### ISSUE THREAD

**Issue by rkumarrb** [reportportal/agent-Python-RobotFramework#19]
Consider I have test case "a" executed with Launch called "New Launch". Now i have a 2nd test case "b", how to make append the result of b to existing launch. If I give the same name in as variable to pybot, it creates new launch like "New Launch #2" 

I can merge the launch in UI but i have very huge number of test cases running so could you please help me on the same to append test executions to existing Launch

Note: First of all, it is a great plugin to robot and its extremely useful to me. Many thanks for the same.

**Comment by iivanou** [comment]
You can pass the id of the launch you want to report to the following way: `--variable RP_LAUNCH_UUID:"id_of_existing_rp_launch"`
