### ISSUE TITLE
Robot's Error and Warning logs are not recognized by listener

### ISSUE THREAD

**Issue by rkumarrb** [reportportal/agent-Python-RobotFramework#20]
I'm getting below warning when I log error or warning with robot framework and add listener to report portal.

Calling method 'log_message' of listener 'robotframework_reportportal.listener' failed: KeyError: 'WARN'
--

Calling method 'log_message' of listener 'robotframework_reportportal.listener' failed: KeyError: 'ERROR'
--

**Comment by rkumarrb** [comment]
We need to add warn and error keys in log_level_mapping dictionary in service.py file like below

log_level_mapping = {
        "INFO": "INFO",
        "FAIL": "ERROR",
        "TRACE": "TRACE",
        "DEBUG": "DEBUG",
        "HTML": "INFO",
        "WARN": "WARN",
        "ERROR": "ERROR"
    }

I thought of create fix and raise pull request as you are already working could you please consider this. Thank you.

**Comment by merlynsoanss** [comment]
Faced the same issue. Fix works for me.. Thank you.
PATH : C:\Python27\Lib\site-packages\robotframework_reportportal\service.py

**Comment by ch-t** [comment]
fixed in #28
