### ISSUE TITLE
Configuration Variable RP_CLIENT_TYPE:SYNC Fails to meet implicit expectations it means comunication doesn't use sync API

### ISSUE THREAD

**Issue by petr-kus** [reportportal/agent-Python-RobotFramework#205]
**Describe the bug**
Configuration Variable RP_CLIENT_TYPE:SYNC Fails to meet implicit expectations it means communication doesn't use sync API

The communication of the client is still done to v2 version of API of the report portal, it means Async.

**Steps to Reproduce**
1. use the configuration in the argument file 
`--loglevel TRACE:INFO
--listener robotframework_reportportal.listener
--variable RP_API_KEY:[xxx]
--variable RP_ENDPOINT:[xxx]
--variable RP_CLIENT_TYPE:SYNC
--variable RP_LAUNCH:[xxx]
--variable RP_PROJECT:admin_personal`

2. execute test with 
`robot --argumentfile argument.cfg test_reportportal.robot`

3. In trace logs you can see it communicate to v2 API (async!)
![log](https://github.com/user-attachments/assets/f93c357b-a063-46b5-899b-d1c18bb13321)

**Expected behavior**
To see communication to v1 API (sync fo reportportal)

**Package versions**
robotframework-reportportal: 5.5.8
reportportal-client: 5.5.10

**Notes**
We encountered this issue after upgrading Report Portal to last version, when the async API broke, and we were unable to restore its functionality. (still trying to fix) Only SYNC API is working for us now.

**Comment by petr-kus** [comment]
Why? Describe... . I don't see this in the documentation anywhere... .

**Comment by HardNorth** [comment]
@petr-kus Yes, it's by design. Sync means synchronous processing, just this. Due to large amount of inner steps RF Agent is designed to work with V2 only.

**Comment by HardNorth** [comment]
@petr-kus If you encountered any issues with backed, please post it to the core project: https://github.com/reportportal/reportportal

It's better for everyone to nail it and fix, than hiding by switching to `V1`.

**Comment by petr-kus** [comment]
@HardNorth Thank you! We will reach out if we are unable to resolve the issue. It seems likely that there is a problem with the configuration of [RabbitMQ](https://reportportal.io/docs/developers-guides/AsynchronousReporting#scheme-of-interactions-between-rabbitmq-and-api) ... or somewhere there. :-(
