### ISSUE TITLE
[Feature Request] Uploading the report.html and log.html of a test run to reportportal 

### ISSUE THREAD

**Issue by moijes12** [reportportal/agent-Python-RobotFramework#29]
As part of my test result, I would want to view the report.html created by the robot framework as these reports are very detailed. This may be provided in the report portal as a an attachment to the test result. I would like to know if there is a way that it can be done right now. For example, can we provide an option like --attachreport true to the run command ?

**Comment by DzmitryHumianiuk** [comment]
@moijes12 it's not provided by agent, not by server.

we do not support logging at the level of launch in versions 4.x
but will make it possible for version 5.x

as a temporary workaround, you can create `@AfterMethod` type of testItem and log required data into it. This type will not affect statistics
