### ISSUE TITLE
Reportportal.io with Robot Framework In Maven/Jenkins Pipeline

### ISSUE THREAD

**Issue by phartheeb** [reportportal/agent-Python-RobotFramework#34]
Hi,

I am able to integrate Robot Framework with Report portal when I running as bat File/in cmd.

Please share do we have the capability to add the report portal to Robot Framework files i.e in .robot file or do we have the maven plugin.

If we do not have maven plugin how to combine the Report portal other plugins with Robot Framework.

Thanks,
Phartheeb Kandasamy

**Comment by DzmitryHumianiuk** [comment]
@reportportal/python-contributors

**Comment by iivanou** [comment]
@phartheeb Could you please shed more light on things you are doing and what you're trying to achieve. What do you mean by saying "add the report portal to Robot Framework files"? This project contains a Python listener for Robot Framework that helps in pushing test results to Report Portal. I'm really confused about your request.
