### ISSUE TITLE
Referencing Selenium Library is not reflected in script file in Eclipse RED ui IDE

### ISSUE THREAD

**Issue by Thangavelpandian** [reportportal/agent-Python-RobotFramework#36]
![1 red xml](https://user-images.githubusercontent.com/40440879/64230583-da43a680-cf0a-11e9-8819-a01cd69896f5.png)
![2 Library not referenced in script file](https://user-images.githubusercontent.com/40440879/64230584-dadc3d00-cf0a-11e9-96d9-9dabe02e887d.png)

We are trying to use selenium library for automating Web based application using Eclipse- RED ui.
Referencing the selenium library in red.xml is not referenced properly and library reference is not reflected in Script file 

Requesting to provide solution to reference the library in Script,keyword directories 

Thanks,
S.Thangavel

![1 red xml](https://user-images.githubusercontent.com/40440879/64230574-d31c9880-cf0a-11e9-901e-ee11cbaf64cb.png)

**Comment by iivanou** [comment]
@Thangavelpandian are you sure that this issue resides in the correct project?

**Comment by iivanou** [comment]
Not related to that project.
