### ISSUE TITLE
Wrong TC status when 'Run Keyword And Expect Error' KW is used

### ISSUE THREAD

**Issue by testautomation** [reportportal/agent-Python-RobotFramework#43]
If a test uses `Run Keyword And Expect Error`  keyword it is displayed as FAILED in Launches although it is PASSED

```robotframework
*** Test Cases ***
Expect Error
    Run Keyword And Expect Error    Expected to FAIL
    ...                             Fail    Expected to FAIL
```

![image](https://user-images.githubusercontent.com/38438046/73277518-92d7f280-41ea-11ea-9b54-bcc24b555226.png)

![image](https://user-images.githubusercontent.com/38438046/73277586-b3a04800-41ea-11ea-9627-9faf3f2c302c.png)

**Comment by iivanou** [comment]
Fixed in #93.
