### ISSUE TITLE
How to send screenshot to report portal- help needed

### ISSUE THREAD

**Issue by Dhams-1** [reportportal/agent-Python-RobotFramework#45]
Hi All @iivanou 

I am very new to reportportal. I have installed agent for robotframework. I would like to send the failure cases screenshots to report portal i went through the code from here https://github.com/reportportal/client-Python#send-attachment-screenshots

but I am not able to follow it on where to add this code snippet. Kindly help me with the same.

**Comment by DzmitryHumianiuk** [comment]
@Dhams-1 it can be outdated.
team working on client-python update, so it should be fixed quite soon.

@iivanou does file sending change?

**Comment by iivanou** [comment]
@Dhams-1 There was an issue with sending log data. Now, it is fixed in version 5.0.1. Could you try it?

**Comment by Dhams-1** [comment]
Hi @iivanou
I updated the to the latest version robotframework-reportportal==5.0.1
I am not able to find the screenshots in case of test failures.  getting the log with image details but it is missing in reportportal
![image](https://user-images.githubusercontent.com/60965197/77906431-3f386280-7288-11ea-8f54-08fc1f0b1e34.png)

is there anything i am missing here. kindly help me with the same

**Comment by iivanou** [comment]
@Dhams-1 Hi, everything works well on my side. Are you sure that you use the full path to the screenshot in your code?

**Comment by Dhams-1** [comment]
@iivanou I am not specifying any explicit path. when i run the robot framework test i do something like this

C:\go\to\testfolder> pybot  --listener robotframework_reportportal.listener --variable RP_UUID:............. **-d Results** .......................-vbrowser:chrome -vbaseurl:

So all the screenshots are saved in the results folder. With Robotframework html report is displayed with the screenshots but in reportportal it is missing.

**Comment by iivanou** [comment]
@Dhams-1 You should report attachments the way it is described in the [docs](https://github.com/reportportal/agent-Python-RobotFramework).

**Comment by Dhams-1** [comment]
@iivanou Sorry i am very new to report portal I went through the code in 
https://github.com/reportportal/client-Python#send-attachement-screenshots

but I was not sure where to add this code snippet.. should i add it in the listener or create my own class file.

**Comment by iivanou** [comment]
You should add this code snippet to the Python module, modify it the way you need, import that module in your Robot file, call created keyword passing a path to the screenshot. It is nothing about Report Portal but rather extending Robot Framework.

**Comment by bharatslalchandani** [comment]
@iivanou: In the code snippet for the screenshot, we need to pass image name but here in execution, we do not know the image name generated by selenium as it is done in an incremented manner (like selenium-screenshot-1,2,3,.. so on) on any step failure. So how can we have that call of the keyword for all the images that get generated by selenium code of any test step failure or waiting for some element ?

**Comment by iivanou** [comment]
@bharatslalchandani I think you can get the image name generated by the selenium and pass it to the keyword that will send it out to RP. That's what I found doing a quick search through the documentation: https://robotframework.org/SeleniumLibrary/SeleniumLibrary.html#Capture%20Page%20Screenshot
