### ISSUE TITLE
Executing tests with pabot results in multiple launch entries

### ISSUE THREAD

**Issue by bioneyez** [reportportal/agent-Python-RobotFramework#48]
I've encountered the following problem:
When I execute the tests using pabot then there is a launch entry for each test case instead of just one.

How can I resolve this issue?

**Comment by iivanou** [comment]
@bioneyez You can contribute to the agent.

**Comment by iivanou** [comment]
What are your versions of both client and agent?

**Comment by bioneyez** [comment]
Agent
```
Name: robotframework-reportportal
Version: 5.0.0
```

Client
```
Name: reportportal-client
Version: 5.0.1
```

I've looked into the issue and found the following: https://libraries.io/pypi/robotframework-reportportal-ng

But it seems like it's discontinued. There is an example script to run with pabot, but I don't know if it is still relevant using the official agent or not. Furthermore there is a bunch of function imported from helper and I couldn't find any implementations for them.

Thanks for the help.

**Comment by iivanou** [comment]
The package you found is a separate package. It's not possible to create the single launch using pabot due to 

> the specific of Robot Framework architecture,  Pabot separates your test suites on multiple tests and runs it in separate processes of pybot.

**Comment by bioneyez** [comment]
Yes I was aware that this is a separate package, but I wanted to make sure that nothing of this sort is implemented. Thanks for the clarification.
