### ISSUE TITLE
Reportportal.io with Robot Framework In Maven

### ISSUE THREAD

**Issue by phartheeb** [reportportal/agent-Python-RobotFramework#53]
Hello All,

I am able to integrate Robot Framework with Report portal when I running as bat File/in cmd.

Please share do we have the capability to add the report portal to Robot Framework files i.e in .robot file or do we have the maven plugin.

If we do not have maven plugin how to combine the Report portal other plugins with Robot Framework.

**Comment by iivanou** [comment]
@phartheeb You can directly report Robot Framework results to RP with the help of this agent.

**Comment by phartheeb** [comment]
Thank you Ivan!

Warm Regards,
Phartheeb Kandasamy

On Apr 3, 2020, at 3:44 AM, Ivan Ivanou <notifications@github.com> wrote:

﻿

@phartheeb<https://github.com/phartheeb> You can directly report Robot Framework results to RP with the help of this agent.
