### ISSUE TITLE
Overall stats don't appear after launch completes [v5]

### ISSUE THREAD

**Issue by iamtech123** [reportportal/agent-Python-RobotFramework#54]
**Describe the bug**
No summary stats (total, passed, failed etc.) are appearing for my launch

**To Reproduce**
I am facing this issue while using Robot Framework integration with Report Portal5
Issue occurs when Test teardown / Suite Teardown is used. Tests are updated when Test teardown / Suite Teardown is removed.

**Screenshots**
![ReportPortal_TestResults_NotUpdated](https://user-images.githubusercontent.com/55270886/78383151-8c546580-75f5-11ea-89ca-03703f87e96e.jpeg)

**Comment by iivanou** [comment]
@iamtech123 Can you test changes from #55?

**Comment by iamtech123** [comment]
When can we expect the merge version to be tested. What would be the merged version number.

**Comment by iivanou** [comment]
@iamtech123 You can test changes without merge. Firstly, the changes must be tested, and only then - released. Not vice versa. I tested PR on my side but wanna get the confirmation from you as well.

**Comment by iamtech123** [comment]
@iivanou, the fix looks stable. I have tried some combinations with Test Setup, Teardown, Suite Setup and Teardown.

**Comment by bharatslalchandani** [comment]
@iivanou: I am also having this issue where if there is test tear down or test setup then overall results does not show up. I need to understand how I can have a master branch code (where resolution is merged) from report portal docker image that is pulled from docker hub??

**Comment by iivanou** [comment]
@bharatslalchandani 5.0.2 has been released.

**Comment by bharatslalchandani** [comment]
@iivanou: 5.0.2 worked like a charm, thanks a lot.
