### ISSUE TITLE
Include multiple test suites in same Launch ID when tests are run in parallel through RobotFramework

### ISSUE THREAD

**Issue by asubair** [reportportal/agent-Python-RobotFramework#61]
Actual:-
Currently, Suppose if my test folder has multiple test suite files, running these test suite files parallel through pabot command will instantiate multiple launch ID's for each of the test suite.

<img width="1105" alt="Home" src="https://user-images.githubusercontent.com/47172975/79757507-dabb7100-8324-11ea-8199-e0aff10d87c6.png">

<img width="1129" alt="ID" src="https://user-images.githubusercontent.com/47172975/79757553-ec9d1400-8324-11ea-8676-05f0938103db.png">

<img width="1098" alt="User" src="https://user-images.githubusercontent.com/47172975/79757580-f32b8b80-8324-11ea-80e1-0ea73e4f348c.png">

Expected:-
All these three suites IDPortal,UserPortal and HomePortal should show within same Launch ID

**Comment by iivanou** [comment]
@asubair Can you try changes from #62? Unfortunately, currently, it's not possible to start launch automatically when using pabot. paabot does not provide any instruments to start something before it starts items in subprocesses.

**Comment by digaetan** [comment]
We use pabot and we now just tested this new agent-Python-RobotFramework and found same issue.

We currently use with Report Portal 5.0.0:
- robotframework-pabot==1.0.0
- robotframework-reportportal-ng==1.0.4.9
- robotframework==3.1.2

And works well, meaning that we get only 1 Launch in Report portal even if pabot starts many thread processes...but we have another small issue with robotframework-reportportal-ng.

**Comment by digaetan** [comment]
Please note that in robotframework-reportportal-ng is possible to pass as comment to  pabot/robot the existing launch ID:

--listener reportportal_listener:{launch_id}

With agent-Python-RobotFramework is not possible, so all robot sub-processes get own launch ID:

--listener robotframework_reportportal.listener

**Comment by iivanou** [comment]
@digaetan robotframework-reportportal-ng is a different package. The package that is released in that repository is called robotframework-reportportal. From what I can see it is NOT possible to pass the ID of existing launch in the robotframework-reportportal-ng as well. There is no such instruction in docs:  _--listener reportportal_listener:{launch_id}_. Please fill up issues for the robotframework-reportportal-ng at the corresponding repository.

**Comment by digaetan** [comment]
@iivanou yes I´m fully aware that robotframework-reportportal-ng is a different package. I was trying to point you there to see how they got it working with Pabot...as it works! we use it and we have a lot of Robot Framework test cases run in parallel with Pabot and 1 single Launch in report Portal which includes all test cases. 
Check for info here https://libraries.io/pypi/robotframework-reportportal-ng

**Comment by iivanou** [comment]
@digaetan  Oke, I looked through the documentation and found what you mean. Unfortunately, the documentation says nothing about that option. As I mentioned above, the fix is provided in #62. @asubair Any updates regarding testing?

**Comment by asubair** [comment]
@iivanou I'll take a look and update

**Comment by asubair** [comment]
@iivanou Each test Suite still appear in separate launches

**Comment by iivanou** [comment]
@asubair How did you start pabot? Can you share the command line?

**Comment by asubair** [comment]
pabot  --processes 3 --listener robotframework_reportportal.listener \
--variable RP_ENDPOINT:http://x.x.x.x \
--variable RP_UUID:xxxxxx-xxxx-xxxx-xxxx-xxxxxxxx \
--variable RP_LAUNCH:Smoke_Test \
--variable RP_PROJECT:smoke_tests  *.robot

**Comment by iivanou** [comment]
@asubair You should add one more variable that indicates launch ID where your tests are goona be reported to like --variable RP_LAUNCH_UUID:"your_launch_id".

**Comment by asubair** [comment]
@iivanou 
Now it works!
Steps:-
Fetch the Launch_ID by calling the API eg:-
```
curl --header "Content-Type: application/json" \
     --header "Authorization: Bearer 039eda00-b397-4a6b-bab1-b1a9a90376d1" \
     --request POST \
     --data '{"name":"rp_launch","description":"My first launch on RP","startTime":"1574423221000","mode":"DEFAULT","attributes":[{"key":"build","value":"0.1"},{"value":"test"}]}' \
     http://rp.com/api/v1/rp_project/launch
```

Pass this Launch_ID as value for RP_LAUNCH_UUID

pabot  --processes 3 --listener robotframework_reportportal.listener \
--variable RP_ENDPOINT:http://x.x.x.x \
--variable RP_UUID:xxxxxx-xxxx-xxxx-xxxx-xxxxxxxx \
--variable RP_LAUNCH:Smoke_Test \
--variable RP_LAUNCH_UUID:"Launch_ID" \
--variable RP_PROJECT:smoke_tests  *.robot


For reference:-
How to start a new launch?
https://github.com/reportportal/documentation/blob/master/src/md/src/DevGuides/reporting.md#start-launch

**Comment by abhijitlocus** [comment]
@iivanou @asubair 
reports are not reflecting on the portal, can you suggest if i am doing something wrong?

i am using -
robotframework==4.0.2
robotframework-pabot==2.0.1
robotframework-seleniumlibrary==4.2.0
robotframework-reportportal-ng==2.0.0
robotframework-reportportal==3.0

running command -
xvfb-run '--server-args=-screen 0 1920x1080x24 -ac' pabot --processes 3 --listener reportportal_listener --variable RP_ENDPOINT:https://reportportal.*****.com/ --variable RP_UUID:*** --variable RP_LAUNCH:*** --variable RP_LAUNCH_UUID:** --variable RP_PROJECT:**** test.robot

**Comment by iivanou** [comment]
@abhijitlocus Remove robotframework-reportportal-ng package and try again.
