### ISSUE TITLE
API robot test execution is very slow [v5]

### ISSUE THREAD

**Issue by iamtech123** [reportportal/agent-Python-RobotFramework#63]
Describe the bug
API robot test execution is very slow

To Reproduce
Execute attached test case file ("RequestLib.txt") with report portal V5.

Actual Result
The test file RequestLib.txt took 1 min while executing in local without RP parameters.
Same test case took more than 7 mins while executing with RP parameters.

Please find the attached reports from above runs.

Library used in the attached test case file : RequestsLibrary - https://marketsquare.github.io/robotframework-requests/

[RequestLib.txt](https://github.com/reportportal/agent-Python-RobotFramework/files/4547490/RequestLib.txt)
[API_Run_WithoutRP.zip](https://github.com/reportportal/agent-Python-RobotFramework/files/4547488/API_Run_WithoutRP.zip)
[API_Run_WithRP.zip](https://github.com/reportportal/agent-Python-RobotFramework/files/4547489/API_Run_WithRP.zip)
![piplist](https://user-images.githubusercontent.com/55270886/80518793-983d0880-89a4-11ea-8971-85eb00c220b1.png)

**Comment by iivanou** [comment]
@iamtech123 Both robotframework-reportportal and your tests are using the requests Python library to establish sessions and to send HTTP requests. The current implementation of the reportportal-client does not support non-blocking HTTP requests that introduce a level of slowness in your tests. However, it is not gonna be solved quickly.

**Comment by iamtech123** [comment]
Thanks @iivanou for the update. Is it possible to have a fix by this quarter(Apr-Jun).

**Comment by iivanou** [comment]
I do not think so.

**Comment by iivanou** [comment]
Closed. Nothing to do on the agent side. The client side will be improved.

**Comment by iamtech123** [comment]
Do we have a followup ticket for this? I need to track this issue / limitation. Could you please help.

**Comment by iivanou** [comment]
There is no issue exist for that. This work is being done within the development of a new client.

**Comment by iamtech123** [comment]
@evjlobanova @iivanou sorry for too much bugging. can i assume that RP V6(Q3 - September) will have the fix or do we have any intermediate release like 5.x.
