### ISSUE TITLE
Support for multithreaded execution with Pabot

### ISSUE THREAD

**Issue by jaasal** [reportportal/agent-Python-RobotFramework#65]
The Robot Framework agent should have support for reporting results from multithreaded Pabot (https://pabot.org/) execution.

It should be done so, that the end result in RP looks excactly like it would in basic Robot FW execution.

**Comment by iivanou** [comment]
@jaasal Actually, it supports reporting with pabot. You should create a new launch at RP and pass its UUID through the RP_LAUNCH_UUID variable. 

Unfortunately, pabot is not multithreaded. It starts test suites in different processes, leaving us without any option to create a new launch automatically.

**Comment by iivanou** [comment]
Actually, they are not the same. They have the same name but the different uuid. The easiest way is to rename your test suites files.

**Comment by jaasal** [comment]
Could you elaborate?

My structure is:
- tests
  - UI
    - 001 Login
        - TEST1
        - TEST2
    - 002 Account
        - TEST1
        - TEST3
  - RESTAPI
     - 001 ProductAPI
        - TEST1
        - TEST2
     - 002 SomeOtherAPI
        - TEST1
        - TEST2
   - FunkyAPI
     - 001 Jazzy Suite
        - TEST1
        - TEST2
and so on...

I think this make perfectly sense in the default HTML report that Robot produces, also I had this working with RP4 but struggling with the new API.

**Comment by iivanou** [comment]
At the previous screenshot I saw test suites reported with the same name "UI". I though the you have a portion of test suites called "UI" located in different folders.
