### ISSUE TITLE
The tag sent through the execution command is not reflecting in the report portal

### ISSUE THREAD

**Issue by rpradhan1904994** [reportportal/agent-Python-RobotFramework#67]
We are integrating our robot framework run into the report portal , but the tag we are sending through the execution command is reflecting in the report portal.

Details :
Python version: Python 3.7.3
Robot framework: Robot Framework 3.1.2
Report Portal: 5.2
Command used for execution:
pabot --processes 6 --exclude env2env --exclude excluded -n noncritical -d results/regression/initial --listener robotframework_reportportal.listener --escape quot:Q --variable RP_ENDPOINT:http://reportportalip:8080 --variable RP_UUID:<Used the UUID from report potal> --variable RP_LAUNCH:"AjeetDemoDryRun3" --variable RP_ATTRIBUTES:"Regressiontest:Runbridges" --variable RP_PROJECT:phm try 

Note: Used the same command with "robot" instead of "pabot" and still the tag is not displaying in the report portal

**Comment by iivanou** [comment]
@rpradhan1904994 I do not see the RP_ATTRIBUTES variable in the list of supported variables.

**Comment by rpradhan1904994** [comment]
My bad i was supposed to mention the below command which includes RP_LAUNCH_TAGS and we were still not have the tags flowing into the report portal.
pabot --processes 6 --exclude env2env --exclude excluded -n noncritical -d results/regression/initial --listener robotframework_reportportal.listener --escape quot:Q --variable RP_ENDPOINT:http://reportportalip:8080 --variable RP_UUID: --variable RP_LAUNCH:"AjeetDemoDryRun3" --variable RP_LAUNCH_TAGS:"Regressiontest:Runbridges" --variable RP_PROJECT:phm try

**Comment by iivanou** [comment]
Duplicates #68
