### ISSUE TITLE
RP_LAUNCH_TAGS names are Not reflecting on the report portal

### ISSUE THREAD

**Issue by login4ajeet** [reportportal/agent-Python-RobotFramework#68]
RP_LAUNCH_TAGS names are Not reflecting on the report portal while running the below pabot commands.
Commands are running fine without any warning or issue except the given tag in the command is not reflecting on the report portal.
Could you please look at this issue and help me out  ?

pabot --listener robotframework_reportportal.listener --escape quot:Q --variable RP_ENDPOINT:end_point_url --variable RP_UUID:3xyz--variable RP_LAUNCH:"AjeetDemoDryRun4" --variable RP_PROJECT:ABC_Project --variable **RP_LAUNCH_TAGS:"TestTag"** RobotTestsFolderName

pabot --listener robotframework_reportportal.listener --escape quot:Q --variable RP_ENDPOINT:end_point_url --variable RP_UUID:3xyz--variable RP_LAUNCH:"AjeetDemoDryRun4" --variable RP_PROJECT:ABC_Project --variable **RP_LAUNCH_TAGS:"SmokeTest:TestTag"** RobotTestsFolderName

Below is the screenshot from report portal and also my expected and result results view.
![image](https://user-images.githubusercontent.com/42564282/89294495-37952a00-d67d-11ea-8414-0e872dcc7ae5.png)

**Comment by login4ajeet** [comment]
@iivanou - Could you please let me know if any update on ETA to fix this as this is blocker for me ?

**Comment by iivanou** [comment]
@login4ajeet ETA is not applicable to this project, it is open source. The issue has been fixed in #69 and will be release soon.

**Comment by iivanou** [comment]
Fixed in 5.0.3 release.

**Comment by login4ajeet** [comment]
@iivanou - Thank you, Its working now.
