### ISSUE TITLE
RP_LAUNCH_TAGS NOT appearing in key and value format on report portal

### ISSUE THREAD

**Issue by login4ajeet** [reportportal/agent-Python-RobotFramework#70]
RP_LAUNCH_TAGS is NOT appearing in key value format on report portal while running the below pabot commands.

pabot --listener robotframework_reportportal.listener --escape quot:Q --variable RP_ENDPOINT:end_point_url --variable RP_UUID:3xyz--variable RP_LAUNCH:"AjeetDemoDryRun6" --variable RP_PROJECT:ABC_Project --variable RP_LAUNCH_TAGS:"**DemoRegression:_DemoTestTag_**" RobotTestsFileFolderName

Actual Result- **DemoRegression:DemoTestTag** is setting up as attribute values on the RP as shown in the screenshot. The attribute keys is empty
Expected Result - **DemoRegression** should show as attribute keys and **DemoTestTag** should show as attribute values

Just for reference old issue-  https://github.com/reportportal/agent-Python-RobotFramework/issues/68

Below is the screenshot from report portal .
![image](https://user-images.githubusercontent.com/42564282/90133103-8bde8f00-dd8c-11ea-966b-fed86125f8b0.png)

**Comment by iivanou** [comment]
What version of the agent are your running? Please, update your agent to the latest version and use RP_LAUNCH_ATTRIBUTES variable name instead.

**Comment by login4ajeet** [comment]
Using robotframework-reportportal     3.1.1

**Comment by login4ajeet** [comment]
@iivanou - Could you please let me know any specific version which will work for attributes key and value ?

**Comment by iivanou** [comment]
ReportPortal version 4?

**Comment by login4ajeet** [comment]
![image](https://user-images.githubusercontent.com/42564282/90135310-1e346200-dd90-11ea-89b7-529f1ee2b797.png)

**Comment by iivanou** [comment]
I mean version of the Report Portal itself, not agent.

**Comment by login4ajeet** [comment]
Its 5.2.1

**Comment by iivanou** [comment]
Update your **agent** to version 5.0.3.

**Comment by login4ajeet** [comment]
Done -
![image](https://user-images.githubusercontent.com/42564282/90147441-d6b5d200-dd9f-11ea-837b-7bf999f5b9e0.png)

**Comment by iivanou** [comment]
Are you able to reproduce your problem with that version?

**Comment by login4ajeet** [comment]
@iivanou - I tried with Report portal version 5.2.0 and below agent version-
![image](https://user-images.githubusercontent.com/42564282/90235850-97d75900-de3f-11ea-9603-d49d3cbfc58f.png)

Problem is now i am unable to see any test results on the report portal. However below commands ran without any error/issue-

pabot --listener robotframework_reportportal.listener --escape quot:Q --variable RP_ENDPOINT:end_point_url --variable RP_UUID:3xyz--variable RP_LAUNCH:"AjeetDemoDryRun6" --variable RP_PROJECT:ABC_Project RobotTestsFileFolderName

pabot --listener robotframework_reportportal.listener --escape quot:Q --variable RP_ENDPOINT:end_point_url --variable RP_UUID:3xyz--variable RP_LAUNCH:"AjeetDemoDryRun6" --variable RP_PROJECT:ABC_Project --variable RP_LAUNCH_ATTRIBUTES:"DemoRegression:DemoTestTag" RobotTestsFileFolderName

pabot --listener robotframework_reportportal.listener --escape quot:Q --variable RP_ENDPOINT:end_point_url --variable RP_UUID:3xyz--variable RP_LAUNCH:"AjeetDemoDryRun6" --variable RP_PROJECT:ABC_Project --variable RP_TEST_ATTRIBUTES:"DemoRegression:DemoTestTag" RobotTestsFileFolderName

**Comment by iivanou** [comment]
Well... Try to remove the robotframework-reportportal-ng package 'cause it provides the same functionality. 5.0.3 agent reports to 5.2.0 Report Portal without issues on my side.

**Comment by login4ajeet** [comment]
@iivanou - The issue was with **six** version . I was using 1.12.0 earlier and didnt work out. so upgraded to 1.15.0 and worked fine. Now i am using below config/version with report portal build 5.2.0 and able to get the attributes and values in proper way on the report portal launch dashboard.

For single attribute- 
pabot --listener robotframework_reportportal.listener --escape quot:Q --variable RP_ENDPOINT:end_point_url --variable RP_UUID:3xyz--variable RP_LAUNCH:"AjeetDemoDryRun8" --variable RP_PROJECT:ABC_Project --variable **RP_LAUNCH_ATTRIBUTES:"regression:tagtestdemoone"** RobotTestsFileFolderName

For multiple attribute- 
pabot --listener robotframework_reportportal.listener --escape quot:Q --variable RP_ENDPOINT:end_point_url --variable RP_UUID:3xyz--variable RP_LAUNCH:"AjeetDemoDryRun8" --variable RP_PROJECT:ABC_Project --variable **RP_LAUNCH_ATTRIBUTES:"regressiondemo:tagtest demoreg:tagtesttwo DemoRegs:tagtestthree"** RobotTestsFileFolderName

![image](https://user-images.githubusercontent.com/42564282/90384678-91471c80-e09f-11ea-8497-205b608820bf.png)

![image](https://user-images.githubusercontent.com/42564282/90385732-2696e080-e0a1-11ea-8fe1-2d174428fc55.png)

Thank you !!!

**Comment by iivanou** [comment]
Welcome!

**Comment by login4ajeet** [comment]
@iivanou - You may close the issue now. Thank you once again for your time and guidance
