### ISSUE TITLE
Error when finishing the test executing the report portal

### ISSUE THREAD

**Issue by nikylimazup** [reportportal/agent-Python-RobotFramework#75]
Hi,

Below, I describe the error that occurs when I execute an instruction when I run my tests using the Robot Framework

[ ERROR ] Calling method 'end_suite' of listener 'reportportal_listener' failed: TypeError: finish_test_item() missing 1 required positional argument: 'item_id'

[ ERROR ] Calling method 'output_file' of listener 'reportportal_listener' failed: AttributeError: 'ReportPortalService' object has no attribute 'base_url'

Command line:

robot --listener reportportal_listener \
--variable RP_ENDPOINT:"http://000.000.0.0:8080" \
--variable RP_UUID:"xxxx-xxxx-xxxx-xxxx" \
--variable RP_LAUNCH:"superadmin_TEST_EXAMPLE" \
--variable RP_PROJECT:"superadmin_personal" \
-d ./log/results tests/login.robot

Could you help me with this, please?

***The Report Portal runs on a VM.***

**Comment by iivanou** [comment]
Versions of agent and client, please... Report Portal version?

**Comment by nikylimazup** [comment]
> Versions of agent and client, please... Report Portal version?

reportportal-client --------> 5.0.5
robotframework-reportportal  --------> 5.0.3
robotframework-reportportal-ng  --------> 2.0.0
report-portal   --------> 2.4
TKS

**Comment by nikylimazup** [comment]
the report is the version docker, I downloaded and installed the project via docker compose. I performed the installation suggested on site.
