### ISSUE TITLE
Error - When finished test using Robot Framework

### ISSUE THREAD

**Issue by nikylimazup** [reportportal/agent-Python-RobotFramework#76]
Hi!
For some reason, my task was closed. But I reopened with the intention of reevaluating the problem based on the beginning of the resolution #75 

Below, I describe the error that occurs when I execute an instruction when I run my tests using the Robot Framework

[ ERROR ] Calling method 'end_suite' of listener 'reportportal_listener' failed: TypeError: finish_test_item() missing 1 required positional argument: 'item_id'

[ ERROR ] Calling method 'output_file' of listener 'reportportal_listener' failed: AttributeError: 'ReportPortalService' object has no attribute 'base_url'

Command line:

robot --listener reportportal_listener
--variable RP_ENDPOINT:"http://000.000.0.0:8080"
--variable RP_UUID:"xxxx-xxxx-xxxx-xxxx"
--variable RP_LAUNCH:"superadmin_TEST_EXAMPLE"
--variable RP_PROJECT:"superadmin_personal"
-d ./log/results tests/login.robot

Could you help me with this, please?

The Report Portal runs on a VM.

reportportal-client --------> 5.0.5
robotframework-reportportal --------> 5.0.3
robotframework-reportportal-ng --------> 2.0.0
report-portal --------> 2.4 (version description in a docker file)

the report is the version docker, I downloaded and installed the project via docker compose. I performed the installation suggested on site.

All services started:
reportportal/service-api:5.3.1
reportportal/service-auto-analyzer:5.3.1
reportportal/service-authorization:5.3.1
reportportal/service-index:5.0.10
rabbitmq:3.7.16-management
postgres:12-alpine
minio/minio:RELEASE.2020-05-01T22-19-14Z
reportportal/service-ui:5.3.1
docker.elastic.co/elasticsearch/elasticsearch:7.3.0
traefik:v2.0.5

TKS

**Comment by iivanou** [comment]
1. Remove the following package - robotframework-reportportal-ng. It's possible that Robot picks up the incorrect listener.
2. Add `-b path_to_log_file` to  your command line in order to save debug output.

**Comment by nikylimazup** [comment]
Thanks, it's works now!
