### ISSUE TITLE
[help required] Error Parsing '--listener' failed: File or directory to execute does not exist.

### ISSUE THREAD

**Issue by vishallanke** [reportportal/agent-Python-RobotFramework#77]
Command => `robot --variable BROWSER:Chrome "D:\Personal\Knowledge\Robot Framework\WebDemo-master\WebDemo-master\login_tests/valid_login.robot" --listener robotframework_reportportal.listener --variable RP_UUID:"*********" --variable RP_ENDPOINT:"http://ec2-.compute.amazonaws.com:8080/api/v1" --variable RP_LAUNCH:"Robot" --variable RP_PROJECT:"SUPERADMIN_PERSONAL"`

Error => `[ ERROR ] Parsing '--listener' failed: File or directory to execute does not exist.`

Tried various options but its not working

**Comment by iivanou** [comment]
Your command is not correctly formed. Put `"D:\Personal\Knowledge\Robot Framework\WebDemo-master\WebDemo-master\login_tests/valid_login.robot"` at the end of the command.

**Comment by vishallanke** [comment]
Yes...below command is working...Thanksfor quick support

`robot --listener robotframework_reportportal.listener --variable RP_UUID:"f70a6457-09e9-4310-9629-3cd8d81cbace" --variable RP_ENDPOINT:"http://ec2-52-66-144-38.ap-south-1.compute.amazonaws.com:8080/api/v1" --variable RP_LAUNCH:"Robot" --variable RP_PROJECT:"SUPERADMIN_PERSONAL" --variable BROWSER:Chrome "D:\Personal\Knowledge\Robot Framework\WebDemo-master\WebDemo-master\login_tests/valid_login.robot" `

**Comment by vishallanke** [comment]
Yes...below command is working...Thanks for quick support

`robot --listener robotframework_reportportal.listener --variable RP_UUID:"*****" --variable RP_ENDPOINT:"http://ec2.compute.amazonaws.com:8080/api/v1" --variable RP_LAUNCH:"Robot" --variable RP_PROJECT:"SUPERADMIN_PERSONAL" --variable BROWSER:Chrome "D:\Personal\Knowledge\Robot Framework\WebDemo-master\WebDemo-master\login_tests/valid_login.robot"`
