### ISSUE TITLE
Tutorial for beginners

### ISSUE THREAD

**Issue by Tset-Noitamotua** [reportportal/agent-Python-RobotFramework#8]
I would like to try ReportPortal with Robot-Framework and Python unittests/pytest. 

In order to better understand things I would like to make a tutorial about that. But I am kind of lost and don't know where to start :-/. So please give me some guidance and I will publish a tutorial in a Github repo or Gist.

So far I have a Ubuntu 16.04 with Docker up and running as a VirtubalBox VM on a Windows host machine. Inside that VM I have ReportPortal running by following the [installation steps from your README](https://github.com/reportportal/reportportal#installation-steps) and your [docs](http://reportportal.io/#documentation/Installation-steps-). I can access ReportPortal UI inside VM at http://localhost:8080. Further I have cloned [Robotframework repository](https://github.com/robotframework/robotframework) which has a great set of over 1500 Python unittests and over 4000 acceptance test in Robot-Framework format. I want to use this tests as example for the integration with ReportPortal.

What I have in short:
- Ubuntu VM with ReportPortal started with `docker-compose up`
- set of Python unittests
- set of RobotFramework tests

What are the next steps I have to work on to see the results of above mentioned tests after execution inside ReportPortal?

**Comment by frizzby** [comment]
Hi @Tset-Noitamotua,
I'm ready to provide some assistance to you. I'm going to replicate your steps now. 
Will get back to you soon with more details.

**Comment by frizzby** [comment]
1. The command to execute RobotFramework acceptance tests with Report Portal looks like this
 `atest/run.py python --listener robotframework_reportportal.listener --variable RP_UUID:"your_uuid" --variable RP_ENDPOINT:"https://endpoint" --variable RP_LAUNCH:”ROBOT” --variable RP_PROJECT:"your_project_name" atest/robot/`
 But likely you will see a few errors #10 #12 #11.

1. Regarding RobotFramework UnitTests. I afraid it will not work in this case since RobotFramework unit tests are implemented with python's [unittest](https://docs.python.org/2/library/unittest.html), but in order to work with ReportPortal unit tests should be executed with [pytest](https://docs.pytest.org/en/latest/).

**Comment by Tset-Noitamotua** [comment]
Great! Thanks a lot!  I will play with that today.

AFAIK pytest claims to be able to deal with Python's regular unittests. So it might be possible to run Robot's unit test with pytest with some tweaking. I'll see what I can find out.

**Comment by Tset-Noitamotua** [comment]
##   Results from first test run
### A) without ReportPortal
```shell
> atest/run.py python atest/robot/
...
Run suite 'Robot' with 4470 tests in 7 minutes 23 seconds 202 milliseconds.

FAILED
4470 critical tests, 4322 passed, 148 failed
4470 tests total, 4322 passed, 148 failed
```

### B) with ReportPortal
```shell
> atest/run.py python --listener robotframework_reportportal.listener --variable RP_UUID:"XXX" \
--variable RP_ENDPOINT:"http://0.0.0.0:8080" \
--variable RP_LAUNCH:"ROBOT FRAMEWORK" \
--variable RP_PROJECT:"ROBOT_INTEGRATION" atest/robot/
...
Run suite 'Robot' with 4470 tests in 14 minutes 28 seconds 791 milliseconds.

FAILED
4470 critical tests, 4322 passed, 148 failed
4470 tests total, 4322 passed, 148 failed
```

@frizzby Did you have similar results?

It's notable that test execution with ReportPortal integration takes twice as much time as without it.


Approx. 15 minutes after test launch ReportPortal still shows the test running. Why? What needs to be done to finish test launch correctly?

The two test launches in screenshot below were created by one test execution. Why did ReportPortal splitt the test run into two lauches?
 
![image](https://user-images.githubusercontent.com/5635462/27527067-170e0cbe-5a4a-11e7-8fc5-866700bb1192.png)

**Comment by Tset-Noitamotua** [comment]
> Regarding RobotFramework UnitTests. I afraid it will not work in this case since RobotFramework unit tests are implemented with python's unittest, but in order to work with ReportPortal unit tests should be executed with pytest.

@frizzby just run [Robot's unittests with pytest](https://github.com/pytest-dev/pytest/issues/2530#issuecomment-311991259) :))))

**Comment by DzmitryHumianiuk** [comment]
@Tset-Noitamotua @frizzby 
Folks, can we have smthn like **Tutorial** from it?

**Comment by HardNorth** [comment]
Not related to the Agent itself
