### ISSUE TITLE
AttributeError: 'ReportPortalService' object has no attribute 'get_system_information'

### ISSUE THREAD

**Issue by YauheniPo** [reportportal/agent-Python-RobotFramework#83]
Hi folks,

I have ERROR when run Robot tests:
> [ ERROR ] Calling method 'start_suite' of listener 'robotframework_reportportal.listener' failed: AttributeError: 'ReportPortalService' object has no attribute 'get_system_information'
> [ ERROR ] Calling method 'start_keyword' of listener 'robotframework_reportportal.listener' failed: IndexError: list index out of range
> [ ERROR ] Calling method 'start_keyword' of listener 'robotframework_reportportal.listener' failed: IndexError: list index out of range
> [ ERROR ] Calling method 'log_message' of listener 'robotframework_reportportal.listener' failed: IndexError: list index out of range
> [ ERROR ] Calling method 'end_keyword' of listener 'robotframework_reportportal.listener' failed: IndexError: pop from empty list
> [ ERROR ] Calling method 'start_keyword' of listener 'robotframework_reportportal.listener' failed: IndexError: list index out of range
> [ ERROR ] Calling method 'start_keyword' of listener 'robotframework_reportportal.listener' failed: IndexError: list index out of range
> [ ERROR ] Calling method 'start_keyword' of listener 'robotframework_reportportal.listener' failed: IndexError: list index out of range
> [ ERROR ] Calling method 'log_message' of listener 'robotframework_reportportal.listener' failed: IndexError: list index out of range
> [ ERROR ] Calling method 'end_keyword' of listener 'robotframework_reportportal.listener' failed: IndexError: pop from empty list
> ...
> ...

My cmd:
`robot --pythonpath . --argumentfile "DEBUG__Pixel_3_API_26_1" "Tests"`

and my DEBUG__Pixel_3_API_26_1.txt file with all test variables:
> ...
>  --listener xxx/Execution/ResultsListener.py
>  --listener robotframework_reportportal.listener
>  --variable RP_UUID:"xxx"
>  --variable RP_ENDPOINT:"https://reportportal.epam.com"
>  --variable RP_LAUNCH:"xxx"
>  --variable RP_PROJECT:"xxx"
>  --variable screenshot_taking:True
>  --variable screen_recording:True
> ...

Python 3.8.6
robotframework-reportportal 5.0.3

**Comment by iivanou** [comment]
Please, update the agent to version 5.0.4. Thx.

**Comment by YauheniPo** [comment]
Thanks, I hope the new version will help. I will update when it is available for pip

**Comment by iivanou** [comment]
@YauheniPo, Try version 5.0.4. It should have been released a week ago but there was an issue with the release procedure on travis.
