### ISSUE TITLE
Not able pass the robot framework - report.html and log.html to Report Portal..

### ISSUE THREAD

**Issue by raymondrajesh26** [reportportal/agent-Python-RobotFramework#84]
Calling method 'end_suite' of listener 'reportportal_listener' failed: TypeError: finish_test_item() missing 1 required positional argument: 'item_id'.

Need help guys.. i am trying to fix for some time but i couldn't do so.. If anyone can throw some light here it would be good.

**Comment by iivanou** [comment]
@raymondrajesh26 What are the versions of the agent, client, Report Portal? Also, if you have the `robotframework-reportportal-ng` package installed, it needs to be removed.

**Comment by iivanou** [comment]
@raymondrajesh26 Is this still actual?
