### ISSUE TITLE
Calling method 'start_test' of listener 'robotframework_reportportal.listener' failed: KeyError: 'critical'

### ISSUE THREAD

**Issue by rdagum** [reportportal/agent-Python-RobotFramework#88]
RobotFramework 4 removed the critical/non-critical functionality from tests and that's causing the listener to fail.

`[ ERROR ] Calling method 'start_test' of listener 'robotframework_reportportal.listener' failed: KeyError: 'critical'
[ ERROR ] Calling method 'end_test' of listener 'robotframework_reportportal.listener' failed: KeyError: 'critical'
Admin Navigates To Calendars Page                                                           | PASS |`

**Comment by rdagum** [comment]
I believe the problems are on these lines:
https://github.com/reportportal/agent-Python-RobotFramework/blob/4ef8e7f09353466a6147a27f1f6eeccc8590895a/robotframework_reportportal/model.py#L33

https://github.com/reportportal/agent-Python-RobotFramework/blob/4ef8e7f09353466a6147a27f1f6eeccc8590895a/robotframework_reportportal/result_visitor.py#L71

https://github.com/reportportal/agent-Python-RobotFramework/blob/4ef8e7f09353466a6147a27f1f6eeccc8590895a/robotframework_reportportal/result_visitor.py#L86

**Comment by iivanou** [comment]
@rdagum The problem is only at line 33 of the model.py. Can you try changes from #89? Thanks.

**Comment by rdagum** [comment]
Information is flowing better now but I got this error in the console (not sure what the impact is in the result):
![image](https://user-images.githubusercontent.com/957733/110852263-c30c1480-8277-11eb-8358-60c6eab7a752.png)

And I also noticed that Suite Setup / Teardowns are shown as "Test" in method type:

![image](https://user-images.githubusercontent.com/957733/110852364-e3d46a00-8277-11eb-98e7-f4285c2f7b5c.png)

**Comment by rdagum** [comment]
It looks like the error is caused because RF4 now reports steps that were not executed when there's a failure.

**Comment by iivanou** [comment]
@rdagum, I've updated PR. Everything seems running smoothly on my side. Can you confirm that?

`And I also noticed that Suite Setup / Teardowns are shown as "Test" in method type`
Your suite structure depth is greater than 2 that is the maximum depth allowed by Report Portal. See [this](https://user-images.githubusercontent.com/30413511/61809181-7a56dc00-ae45-11e9-84f2-80573f08268f.png) picture. All items which exceed that limit will be considered to be tests or steps.

**Comment by rdagum** [comment]
Everything looks good now.
Thanks for clarifying about the suite depth. Not a big deal as the total number of tests is correct.
